config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :spiders
  post '/spiders/task/:state', to: 'spiders#task', as: 'task_spider'
  post '/spiders/start/:id', to: 'spiders#start', as: 'start_spider'

  root 'spiders#index'

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/spider.rb
class Spider < ActiveRecord::Base
	validates :url, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  ActiveJob::Base.queue_adapter = :sidekiq

  helper_method :current_user
  
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
  	redirect_to login_path if !current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		redirect_to root_path if current_user
		render :layout => 'empty'
	end

	def create
		user = User.find_by username: params[:username]
		if user && user.try(:authenticate, params[:password])
			session[:user_id] = user.id
			flash[:notice] = "欢迎使用新闻抓取系统"
		else
			flash[:error] = "用户名或密码错误, 请重试"
		end
		redirect_to root_path
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "成功登出"
    redirect_to login_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :password)
	end

end

app/controllers/spiders_controller.rb
require 'sidekiq/api'
class SpidersController < ApplicationController
	before_action :require_login
	def index
		@spiders = Spider.all
	end

	def new
		@spider = Spider.new()
	end

	def create
		@spider = Spider.new(spider_params)
		@spider.source = Digest::MD5.hexdigest @spider.url
		@spider.status = 0
		@spider.save
		redirect_to spiders_path
	end

	def edit
		@spider = Spider.find(params[:id])
	end

	def update
		@spider = Spider.find(params[:id])
		@spider.update(spider_params)
		redirect_to spiders_path
	end

	def destroy
		spider = Spider.find(params[:id])
		spider.destroy
		redirect_to spiders_path
	end

	def start
		sleep(0.5.seconds)
		@spider = Spider.find(params[:id]) 
		@spider.status = (@spider.status - 1).abs
		if @spider.save && whether_start_job(@spider)
			# 启动任务
			SpiderJob.perform_later(@spider.url, @spider.source)
		end
	end

	# def task
	# 	# @task_state = params[:state].to_i
	# 	# queue = Sidekiq::Queue.new("task_manage")
	# 	# puts "task_manage queue size #{queue.size}"
	# 	# if @task_state > 0 && queue.size == 0
	# 		TaskManagerJob.perform_later
	# 	# end

	# 	queue = Sidekiq::Queue.new(:task_manage)
	# 	puts "task_manage queue.size = #{queue.size}"

	# 	workers = Sidekiq::Workers.new
	# 	puts workers.size 
	# 	workers.each do |process_id, thread_id, work|
	# 		puts work.class
	# 	end

	# 	# Sidekiq.redis do |r| 
 #  # # r.srem "queues", "app_queue"
 #  # # r.del  "queue:app_queue"
 #  # 		puts r
	# 	# end

	# 	# queue = Sidekiq::Queue.new
	# 	# puts "default queue size #{queue.size}"
 #  #   puts queue.size
	# 	# respond_to do |format|
	# 	# 	format.js
	# 	# end
	# end

	private 
	def spider_params
		params.require(:spider).permit!
	end

	def whether_start_job(spider)
		#清理ScheduledSet和Queue队列
		#将于spider.source相同的任务都删除掉
		puts "scheduledSet"
		scheduled = Sidekiq::ScheduledSet.new
		scheduled.each do |job|
			job_hash = job.args[0]
			if job_hash['arguments'][1] == spider.source
				job.delete
				puts "delete #{spider.source}"
			end
		end

    puts "queue"
    queue = Sidekiq::Queue.new
		queue.each do |job|
			job_hash = job.args[0]
			if job_hash['arguments'][1] == spider.source
				job.delete
				puts "delete #{spider.source}"
			end
		end

		#关闭状态，则不再启动任务
		if spider.status == 0
			return false
		end

		#如果是开启状态，且有与spider.source相同的任务在执行
		#则无需再启动任务
		puts "workers"
		workers = Sidekiq::Workers.new
		workers.each do |process_id, thread_id, work|
			if work['payload']['args'][0]['arguments'][1] == spider.source
				return false
			end
		end

		#排除万难，启动任务
		return true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

app/helpers/spiders_helper.rb
module SpidersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div>
        <strong>Copyright</strong> 宾果信息技术 &copy; 2016-2017
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">管理员</strong>
                            </span> 
                        </span>
                    </a>
                </div>
                <div class="logo-element">
                    新闻+
                </div>
            </li>
            <li class="<%= 'active' if current_page?('/') %>">
                <%= link_to "/" do %>
                <i class="fa fa-bug"></i> <span class="nav-label">爬虫列表</span>
                <% end %>
            </li>
        </ul>

    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a data-no-turbolink='true' class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message" data-i18n="topnav.welcometext">欢迎使用新闻抓取管理系统</span>
            </li>
            <li>
                <%= link_to logout_path do %>
                    <i class="fa fa-sign-out"></i> 注销
                <% end %>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>新闻抓取系统</title>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>
    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        <%= render 'layouts/navigation' %>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>

            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <%= yield :javascript %>

</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>新闻抓取系统</title>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>



</head>
<body class="gray-bg">

<!-- Main view  -->
<%= yield %>


    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

</body>
</html>

app/views/spiders/_form.html.erb
<%= form_for @spider, :html => {:class => 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
    <%= f.label :url, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :url, :class => "form-control", :required => true %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
    <%= f.label :rule, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :rule, :class => "form-control" %>
    </div>
  </div>
  <div class="hr-line-dashed"></div>

  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
        <%= f.submit '提交', :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/spiders/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
      	<div class="row">
          <div class="col-sm-4 m-b-xs">
          	<%= link_to '< 返回', spiders_path, {:class => "btn btn-primary btn-outline"} %>
        	</div>
        	<div class="col-sm-4 m-b-xs">
        		<h5>修改规则</h5>
        	</div>
        </div>
      </div>
      <div class="ibox-content">
      	<%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
        $("#edit_spider").validate({
            rules: {
                url: {
                    required: true,
                    url: true
                }
            }
        });

    });
  </script>
<% end %>

app/views/spiders/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <div class="row">
            <div class="col-sm-5 m-b-xs">
              <%= link_to '+ 新建', new_spider_path, {:class => "btn btn-primary btn-outline"} %>
            </div>
            <div class="col-sm-4 m-b-xs">
            </div>
              <div class="col-sm-3">
                <div class="input-group">
                  <input type="text" placeholder="爬虫名称" class="input-sm form-control"> 
                  <span class="input-group-btn">
                    <button type="button" class="btn btn-sm btn-primary"> 搜索</button>
                  </span>
                </div>
              </div>
          </div>
        </div>
        <div class="ibox-content">
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th></th>
                  <th>名称 </th>
                  <th>网址 </th>
                  <th>状态 </th>
                  <th>操作 </th>
                </tr>
              </thead>
              <tbody>
                <% @i=0 %>
                <% @spiders.each do |spider| %>
                  <tr>
                    <td><%= @i=@i+1 %></td>
                    <td><%= spider.title %></td>
                    <td><%= spider.url %></td>
                    <!-- <td><%= spider.rule %></td> -->
                    <td>
                      <% 
                        @status_link_id = "spider#{spider.id}"
                        if spider.status > 0
                          @status = "已启动"
                          @label_class = "ladda-button btn btn-info"
                        else
                          @status = "已停止"
                          @label_class = "ladda-button btn btn-warning"
                        end 
                      %>
                      <div>
                        <%= link_to @status, start_spider_path(spider.id), {:id =>@status_link_id, :method=> :post, :remote => true, :data => {style:"slide-left"}, :class => @label_class} %> 
                      </div>
                    </td>
                    <td>
                      <%= link_to edit_spider_path(spider.id), {:class => "btn btn-info btn-outline"} do %>
                        <i class="fa fa-paste"></i> 编辑
                      <% end %>
                      <%= link_to spider_path(spider.id), {:method => :delete, :data => {confirm: "确定删除？"}, :class=> "btn btn-danger btn-outline"} do %>
                        <i class="fa fa-warning"></i> 删除
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<% content_for :javascript do %>
<script type="text/javascript">

  $(function() {
    $( '.ladda-button' ).ladda( 'bind', { timeout: 10000 } );

    var notice = "<%= flash[:notice] %>"
    if (notice) {
      setTimeout(function() {
        toastr.options = {
            closeButton: true,
            progressBar: true,
            showMethod: 'slideDown',
            timeOut: 2000
        };
        toastr.success(notice, '提示');
      }, 500);
    }
  });

</script>
<% end %>

app/views/spiders/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
      	<div class="row">
          <div class="col-sm-4 m-b-xs">
          	<%= link_to '< 返回', spiders_path, {class: "btn btn-primary btn-outline"} %>
        	</div>
        	<div class="col-sm-4 m-b-xs">
        		<h5>新建规则</h5>
        	</div>
        </div>
      </div>
      <div class="ibox-content">
      	<%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
        $("#new_spider").validate({
            rules: {
              url: {
                    required: true,
                    url: true
              }
            }
        });

    });
  </script>
<% end %>

app/views/spiders/old_index.html.erb
<h1>爬虫列表</h1>
<%= link_to '添加规则', new_spider_path %>
<%= link_to @task_state, task_spider_path(@task_state == 0 ? 1 : 0), method: :post, remote: true %> 

<table>
	<tr>
		<th>名称</th>
		<th>网址</th>
		<th>规则</th>
		<th>操作</th>
  </tr>
  <% @spiders.each do |spider| %>
  <tr>
  	<td><%= spider.title %></td>
  	<td><%= spider.url %></td>
  	<td><%= spider.rule %></td>
  	<td>
  		<%= link_to spider.status, start_spider_path(spider.id), method: :post, remote: true %> 
  		<%= link_to "编辑", edit_spider_path(spider.id) %>
  		<%= link_to "删除", spider_path(spider.id), method: :delete, data: {confirm: "确定删除？"} %>
  	</td>
  </tr>
  <% end %>
</table>

app/views/spiders/start.js.erb
var a = $("#spider<%= @spider.id %>");
a.ladda().ladda('stop');

var status = <%= @spider.status %>;
var text, label_class;
if (status > 0) {
  a.find(".ladda-label").text("已启动");
  a.removeClass("btn-warning").addClass("btn-info");
} else {
  a.find(".ladda-label").text("已停止");
  a.removeClass("btn-info").addClass("btn-warning");
} 